language: android
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=20 LINT=true MAVEN=true
  global:
  - TERM=dumb
  - COMPONENTS=build-tools-20.0.0,android-20,extra-android-m2repository,extra-android-support,extra-google-m2repository
  - LICENSES="android-sdk-license-5be876d5|android-sdk-preview-license-52d11cd2"
  # nexusUsername
  - secure: vq6VqKOxxOWi2jp6IwqWJyyEUDqc8ijCjBxn2R9JQqqiJMnyj3e+MkYGnCTpZxrs5H6OakeBR2S5vYg0vVXoYuSSQTIkYQk9tbR5haKsSsXV8Fs6xj+si2C8D0ZoIn8QIrCeKT2SNEBH4lWLXoivl64bGs0j/U7HRKIYRs5hmV4=
  # nexusPassword
  - secure: hnVoFZQUiM7plZfOrZ8asfOv2r9kLuXFc9HLLejyOx57ZVFjSdhIiD8pEEtnEKb71hGHwcxiyYPBs10Rripk8Z4d1vboTl7RyMLdd0VkH1Poy9xsi1yZhobCvZLyhMcdSOwQwsjK9AP/zVrc6qsmz5liNDUmfNnDNeJeVDKmifs=
before_install:
- curl -3L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer
  | bash /dev/stdin --install=$COMPONENTS,android-$ANDROID_TARGET,sys-img-armeabi-v7a-android-$ANDROID_TARGET
  --accept=$LICENSES && source ~/.android-sdk-installer/env
before_script:
- gradle
install:
- true
script:
- if [[ $LINT == 'true' ]]; then gradle lint ; fi
after_success:
- if [[ $MAVEN == 'true' && $TRAVIS_BRANCH == 'dev' && $TRAVIS_PULL_REQUEST == 'false'
  ]]; then gradle clean uploadArchives -PnexusUsername=$nexusUsername -PnexusPassword=$nexusPassword --info
  ; fi
notifications:
  email: false
